### PR TITLE
Compensate for deleted COP nextstate instructions

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Comment by karenetheridge** [comment]
Maintainer note - this replaces:
https://github.com/jbenjore/B-Utils/pull/6
https://github.com/jbenjore/B-Utils/pull/11

**Comment by karenetheridge** [comment]
@rocky There were lots of conflicts with these commits (please in future _rebase_ your commits, rather than simply merging) -- my attempt to rebase and resolve them is here in this branch -- https://github.com/karenetheridge/B-Utils/tree/topic/deleted_COP_nextstate -- please confirm that this is your intent. It wasn't clear what "fix a small bug" was referring to; can you clarify? Also, it doesn't look like there are any tests that cover your change. Can you add some?

**Comment by rocky** [comment]
Actually on second thought let's just kill this and the pull requests. It's possibly or probable that Father C's change addressed this.  Or Perl has changed to deal with this this problem. At this point 3 years later, I don't really care and don't use Perl enough that any of this matters, and I've spend far more time on this than I can afford to spend.

**Comment by rurban** [comment]
Actually it's a good feature, and simplifies the walker and its test. I took it over to B::Utils1 https://github.com/rurban/B-Utils1/commit/760251592ffa0582d9b9a1a3b3c7c7cba4c202b4
Thanks

**Pull request closed without merging**
